version: '3.9'
services:
  backend:
    build: ./ai-chat-lab   
    ports:
      - "8080:8080"
    networks:
      - chat-net

  frontend:
    build: ./UI-V0.1/UI-test-version
    ports:
      - "3000:80"
    environment:
      - VITE_API_URL=http://backend:8080
    depends_on:
      - backend
    networks:
      - chat-net

networks:
  chat-net:
    driver: bridge
